### ISSUE TITLE
Package the output into a more readable format

### ISSUE THREAD

**Issue by sampreets3** [APLA-Toolbox/PythonPDDL#53]
The current output of the planning problem is difficult to interpret for someone who does not know what to look for. For example, the current solution provided is something like the following: 
```
[(<PyCall.jlwrap flip_row(r1)>, 1), (<PyCall.jlwrap flip_row(r3)>, 1), (<PyCall.jlwrap flip_column(c2)>, 1)]
Computation time: 18.53
```

It would be more preferable to have the output in a much simpler fashion, something like : 
```
flip_row(r1), 1
flip_row(r3), 1
flip_row(c2), 1
```
I think this might be easily achieved by storing the output and trimming off the unnecessary bits, but we'll see about that during implementation.

**Comment by guilyx** [comment]
There should be a python native function to remove all iterations of a substring of a string
From that you should be able to fix this by just removing `<PyCall.jlwrap ` (with the trailing space) and `>`

Wrap this into a method of Node called `__str__(self)` so it overloads the string operator.

Tell me if you need an example for the overloading

**Comment by guilyx** [comment]
`<PyCall.jlwrap flip_row(r1)>`

This is an action, but we have no class for that. A way to pretty print it would be:
- Create an Action class
- Init with a self.jlwrap_action = jlwrap_action, self.cost = cost
- Add `__str__` method implementing the above script to remove unreadable aspect, and add the cost too
- `AutomatedPlanner.get_actions_from_path` would then return a pretty printed list of objects of type Action.



The problem also lies with is the attribute `state` of a class `Node`. We have a method `get_states_from_path` in AutomatedPlanner that returns a list of the julia states. What we should do is:

- Add the `__str__` method to `Node` to pretty print important fields: attributes `state` and `g_cost` should be enough (I don't remember what a state look like so you'll have to investigate yourself [just use get_states_from_path in main instead of get_actions_from_path I guess])
- Ditch the `get_states_from_path` entirely
- Now when we print(path) that is output of a search algorithm, it should be pretty
